import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";     
    
//core
import "primereact/resources/primereact.min.css";  

//icons
import "primeicons/primeicons.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Real Inventario',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
     
        {children}
        
        </body>
    </html>
  )
}
